name: C/C++ CI

env:
  BINTRAY_USER: manromen
  CONAN_REPOSITORY: https://api.bintray.com/conan/manromen/rgpaul
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable
  LIBRARY_VERSION: 2.9.2

on:
  push:
    branches:
      - master

jobs:
  # build for ios
  build_ios:
    runs-on: macOS-10.14
    env:
      GITHUB_OS_NAME: macos
      DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
#        ref: ${{ GITHUB_REF }}
    - name: install conan
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-setup.sh
    - name: create conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/build-ios.sh
    - name: deploy conan packages
      run: ${GITHUB_WORKSPACE}/.github/scripts/conan-deploy.sh
